-- ==========================================================
-- Divine Store (DivyaStore) - Oracle Database Schema (DDL)
-- Compatible with Oracle Database 12c, 19c, 21c, 23ai Free
-- ==========================================================

-- Clean up existing tables safely if re-running
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE order_items CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE categories CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- ----------------------------------------------------------
-- 1. CATEGORIES TABLE
-- ----------------------------------------------------------
CREATE TABLE categories (
    category_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name   VARCHAR2(100) NOT NULL UNIQUE,
    slug            VARCHAR2(100) NOT NULL UNIQUE,
    description     VARCHAR2(500),
    icon            VARCHAR2(50)
);

-- ----------------------------------------------------------
-- 2. PRODUCTS TABLE
-- ----------------------------------------------------------
CREATE TABLE products (
    product_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     NUMBER NOT NULL,
    name            VARCHAR2(200) NOT NULL,
    slug            VARCHAR2(200) NOT NULL,
    description     VARCHAR2(2000),
    price           NUMBER(10, 2) NOT NULL,
    original_price  NUMBER(10, 2),
    stock_quantity  NUMBER DEFAULT 0 NOT NULL,
    rating          NUMBER(3, 1) DEFAULT 5.0,
    review_count    NUMBER DEFAULT 0,
    image_url       VARCHAR2(500),
    is_featured     NUMBER(1) DEFAULT 0 CHECK (is_featured IN (0, 1)),
    tag             VARCHAR2(50),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prod_category FOREIGN KEY (category_id) REFERENCES categories(category_id) ON DELETE CASCADE
);

-- ----------------------------------------------------------
-- 3. ORDERS TABLE
-- ----------------------------------------------------------
CREATE TABLE orders (
    order_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number     VARCHAR2(50) NOT NULL UNIQUE,
    customer_name    VARCHAR2(150) NOT NULL,
    customer_email   VARCHAR2(150) NOT NULL,
    customer_phone   VARCHAR2(30) NOT NULL,
    shipping_address VARCHAR2(500) NOT NULL,
    payment_method   VARCHAR2(50) DEFAULT 'UPI' NOT NULL,
    payment_status   VARCHAR2(50) DEFAULT 'COMPLETED' NOT NULL,
    total_amount     NUMBER(10, 2) NOT NULL,
    order_status     VARCHAR2(50) DEFAULT 'CONFIRMED' NOT NULL,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------------------------------------
-- 4. ORDER_ITEMS TABLE
-- ----------------------------------------------------------
CREATE TABLE order_items (
    order_item_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        NUMBER NOT NULL,
    product_id      NUMBER NOT NULL,
    product_name    VARCHAR2(200) NOT NULL,
    quantity        NUMBER(5) NOT NULL,
    unit_price      NUMBER(10, 2) NOT NULL,
    subtotal        NUMBER(10, 2) NOT NULL,
    CONSTRAINT fk_item_order FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
    CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- Indexes for performance
CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_orders_created ON orders(created_at DESC);
CREATE INDEX idx_order_items_order ON order_items(order_id);

-- ----------------------------------------------------------
-- SEED DATA: CATEGORIES
-- ----------------------------------------------------------
INSERT INTO categories (category_id, category_name, slug, description, icon) VALUES 
(1, 'Sacred Idols & Statues', 'idols', 'Handcrafted brass, panchaloha, and marble murtis of revered deities', 'om');

INSERT INTO categories (category_id, category_name, slug, description, icon) VALUES 
(2, 'Incense & Fragrances', 'incense', 'Pure floral agarbattis, natural loban, dhoop cups and attar', 'fire');

INSERT INTO categories (category_id, category_name, slug, description, icon) VALUES 
(3, 'Pooja Essentials', 'pooja-essentials', 'Complete pooja thalis, sacred waters, kumkum, and havan samagri', 'spa');

INSERT INTO categories (category_id, category_name, slug, description, icon) VALUES 
(4, 'Sacred Malas & Yantras', 'malas-yantras', 'Authentic certified Rudraksha malas, Sphatik, Tulsi and energized Yantras', 'gem');

INSERT INTO categories (category_id, category_name, slug, description, icon) VALUES 
(5, 'Brass & Copper Vesssels', 'brass-copper', 'Auspicious deepams, kalash, panchapatra and bell sets', 'award');

-- ----------------------------------------------------------
-- SEED DATA: PRODUCTS
-- ----------------------------------------------------------
INSERT INTO products (product_id, category_id, name, slug, description, price, original_price, stock_quantity, rating, review_count, image_url, is_featured, tag) VALUES
(1, 1, 'Antique Brass Ganesha with Prabhavali (6 inch)', 'brass-ganesha-prabhavali-6in', 'Exquisitely handcrafted pure brass Lord Ganesha idol with ornate floral arch. Brings prosperity, removes obstacles, and radiates serene spiritual energy into your home altar or entrance.', 1899.00, 2499.00, 25, 4.9, 128, 'ganesha.jpg', 1, 'BESTSELLER');

INSERT INTO products (product_id, category_id, name, slug, description, price, original_price, stock_quantity, rating, review_count, image_url, is_featured, tag) VALUES
(2, 2, 'Natural Mysore Sandalwood Agarbatti (150g)', 'mysore-sandalwood-agarbatti', 'Pure organic sandalwood paste hand-rolled into slow-burning incense sticks. Completely charcoal-free with lingering sacred fragrance for meditation and daily worship.', 349.00, 450.00, 150, 4.8, 210, 'incense_sandal.jpg', 1, 'ORGANIC');

INSERT INTO products (product_id, category_id, name, slug, description, price, original_price, stock_quantity, rating, review_count, image_url, is_featured, tag) VALUES
(3, 5, 'Ashtalakshmi Brass Oil Diya (Deepam)', 'ashtalakshmi-brass-diya', 'Heavy solid brass traditional oil lamp embossed with the eight forms of Goddess Lakshmi. Holds generous oil for long-lasting devotional flames.', 1250.00, 1600.00, 40, 4.9, 87, 'diya_lakshmi.jpg', 1, 'AUSPICIOUS');

INSERT INTO products (product_id, category_id, name, slug, description, price, original_price, stock_quantity, rating, review_count, image_url, is_featured, tag) VALUES
(4, 4, 'Original 5-Mukhi Nepali Rudraksha Mala (108 Beads)', '5-mukhi-nepali-rudraksha-mala', 'Lab-certified 5 Mukhi authentic Nepali Rudraksha beads strung on pure red silk thread with silver capping. Renowned for peace, mental clarity, and blood pressure balance.', 1499.00, 2200.00, 30, 5.0, 340, 'rudraksha_mala.jpg', 1, 'CERTIFIED');

INSERT INTO products (product_id, category_id, name, slug, description, price, original_price, stock_quantity, rating, review_count, image_url, is_featured, tag) VALUES
(5, 3, 'Complete Traditional Brass Pooja Thali Set (8 Pcs)', 'complete-brass-pooja-thali-set', 'Complete set including 10-inch engraved Thali, Panchapatra, Udharani spoon, Bell (Ghanti), Agarbatti stand, Diya, and Chandan bowls. Perfect for housewarming & festive gifts.', 2199.00, 2999.00, 18, 4.8, 95, 'pooja_thali.jpg', 1, 'MUST HAVE');

INSERT INTO products (product_id, category_id, name, slug, description, price, original_price, stock_quantity, rating, review_count, image_url, is_featured, tag) VALUES
(6, 2, 'Ayurvedic Sambrani Loban Dhoop Cups (Pack of 24)', 'ayurvedic-sambrani-loban-cups', 'Made from natural cow dung charcoal base filled with pure Guggal, Loban and aromatic herbs. Purifies indoor air and dispels negative energies.', 299.00, 399.00, 200, 4.7, 164, 'sambrani_cup.jpg', 0, 'POPULAR');

INSERT INTO products (product_id, category_id, name, slug, description, price, original_price, stock_quantity, rating, review_count, image_url, is_featured, tag) VALUES
(7, 3, 'Gangotri Holy Gangajal in Sealed Brass Kalash (500ml)', 'gangotri-holy-gangajal-brass-kalash', 'Pristine, tested holy water sourced directly from the heights of Gangotri. Packaged in a leak-proof sanctified brass Kalash for Abhishekam and domestic sanctification.', 599.00, 750.00, 60, 4.9, 78, 'gangajal.jpg', 0, 'HOLY WATER');

INSERT INTO products (product_id, category_id, name, slug, description, price, original_price, stock_quantity, rating, review_count, image_url, is_featured, tag) VALUES
(8, 4, 'Pure Sphatik (Quartz Crystal) Shri Yantra (100g)', 'sphatik-shri-yantra', 'Carved out of single flawless crystal quartz according to sacred geometry. Radiates immense positive vibration and wealth magnetizing energies.', 1850.00, 2400.00, 15, 4.9, 52, 'shri_yantra.jpg', 1, 'RARE');

INSERT INTO products (product_id, category_id, name, slug, description, price, original_price, stock_quantity, rating, review_count, image_url, is_featured, tag) VALUES
(9, 1, 'Panchaloha Dancing Shiva (Nataraja) 8 inch', 'panchaloha-nataraja-8in', 'Masterpiece sculpture of Cosmic Dancer Nataraja cast in classical five-metal alloy (Panchaloha). Intricate craftsmanship capturing cosmic balance.', 3450.00, 4800.00, 12, 5.0, 44, 'nataraja.jpg', 1, 'EXCLUSIVE');

INSERT INTO products (product_id, category_id, name, slug, description, price, original_price, stock_quantity, rating, review_count, image_url, is_featured, tag) VALUES
(10, 5, 'Pure Copper Tamra Jal Hammered Water Pot (2 Litres)', 'pure-copper-water-pot-2l', 'Hand-hammered 99.7% pure Ayurvedic copper storage vessel. Naturally enriches water with essential minerals and supports digestive wellness.', 1350.00, 1800.00, 35, 4.6, 63, 'copper_pot.jpg', 0, 'WELLNESS');

INSERT INTO products (product_id, category_id, name, slug, description, price, original_price, stock_quantity, rating, review_count, image_url, is_featured, tag) VALUES
(11, 4, 'Vrindavan Sacred Tulsi Wood Japa Mala (108 Beads)', 'vrindavan-tulsi-wood-japa-mala', 'Natural Shyam Tulsi wood beads sourced from the sacred grove of Vrindavan. Smoothly polished for effortless daily mantra chanting and spiritual serenity.', 450.00, 600.00, 80, 4.8, 112, 'tulsi_mala.jpg', 0, 'DEVOTIONAL');

INSERT INTO products (product_id, category_id, name, slug, description, price, original_price, stock_quantity, rating, review_count, image_url, is_featured, tag) VALUES
(12, 1, 'Pure White Marble Dust Saraswati Idol (7 inch)', 'marble-saraswati-idol-7in', 'Graceful figurine of Goddess of Knowledge and Arts holding the holy Veena. Finished with durable gold leaf accents.', 1699.00, 2299.00, 20, 4.9, 39, 'saraswati.jpg', 0, 'EDUCATION');

COMMIT;
